import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/styles/tailwind.css";
import { Layout } from "@/components/layout/Loyout";

const gothicRegular = localFont({
  src: "../public/fonts/GOTHIC.ttf",
  variable: "--font-gothic-regular",
  weight: "400",
});

const gothicBold = localFont({
  src: "../public/fonts/gothicb.ttf",
  variable: "--font-gothic-bold",
  weight: "700",
});

const gothicItalic = localFont({
  src: "../public/fonts/gothici.ttf",
  variable: "--font-gothic-italic",
  weight: "400",
  style: "italic",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={`${gothicRegular.variable} ${gothicBold.variable} ${gothicItalic.variable} antialiased`}
        style={{ fontFamily: "var(--font-gothic-regular)" }}
      >
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
